### ISSUE TITLE
Setup CircleCI testing workflow

### ISSUE THREAD

**Issue by timoludwig** [digitalfabrik/integreat-compass#7]
As soon as basic tests are implemented, we should execute them for every PR.
Add a small CircleCI workflow loosely based on the [integreat-cms workflow](https://github.com/digitalfabrik/integreat-cms/blob/68a3810c3b20cc83d1fb93d71e6ed5af60f591dc/.circleci/config.yml#L250-L279)

```
  test:
    docker:
      - image: cimg/python:3.9
      - image: cimg/postgres:14.1
        environment:
          POSTGRES_USER: integreat_compass
          POSTGRES_DB: integreat_compass
          POSTGRES_PASSWORD: password
    resource_class: small
    parallelism: 16
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Enable virtual environment
          command: echo "source .venv/bin/activate" >> $BASH_ENV
      - run:
          name: Migrate database
          command: integreat-compass-cli migrate
      - run:
          name: Run tests
          command: pytest --circleci-parallelize --disable-warnings --cov=integreat_compass --cov-report xml --junitxml=test-results/junit.xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
```

Whether we want to store the test coverage somewhere is another question.
Do we want to use an external tool for this? (e.g. CodeClimate is able to parse the partial coverage results returned from the CircleCI parallelization

This is blocked by:
- #6
